### PR TITLE
Page Style Enhancement and Currency change option.

### PR DESCRIPTION
**Pull request by ghost**
I had done some major changes in the looks of this web page using SASS so that, it will support in most of the browsers without any issue. There is a one new option for selecting a currency, according to selected currency user will get there tip amount in that currency.

### CODE REVIEW

**Comment by ghost** [comment]
@rishikesh2003  Please merge these changes.

**Comment by rkeshs** [comment]
I am reviewing your changes please wait. Appreciate your patience.

**Comment by ghost** [comment]
Ok ok, By the way I had already checked the output of  complete code and all the input fields. You can too from: 
https://kotnurpj.github.io/tipapp-javascript/

**Review by rishikesh2003 — APPROVED** [review]

**Comment by rkeshs** [comment]
I have a plan to migrate all my repos to typescript so i will change your jquery file to typescript one day. Thanks for the contribution

**Comment by ghost** [comment]
Ok fine, however typescript is being used alot nowadays & you're welcome.

**Pull request merged**
